### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by biorisk** [Skarlso/google-oauth-go-sample#4]
Thanks for this useful example, unfortunately I cannot borrow from it without a license. Would you consider adding a license? Preferably MIT or Apache. (Described here: https://help.github.com/en/articles/adding-a-license-to-a-repository)

**Comment by Skarlso** [comment]
Sure. :) I'll add one.

**Comment by Skarlso** [comment]
@biorisk Done :) And thanks! :)

**Comment by biorisk** [comment]
Awesome. Saved me a lot of time!

**Comment by Skarlso** [comment]
\o/
